defaults:
  - template: required
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null
  run:
    dir: .

seed: 0
dtype: auto
param_dtype: auto
qconfig: null
mesh: auto

max_len: null
temperature: 0.0
top_k: -1
top_p: 1.0
max_new_tokens: null

peft: null
model: null
checkpoint: null

# Chat CLI
style: rich

# Chat API Server
host: 127.0.0.1
port: 8000

# Eval
batch_size: 8
data_dir: null
padding_side: null

debug: False
