defaults:
  - template: required
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:  
  output_subdir: null
  run:
    dir: .

seed: 0
dtype: auto
param_dtype: auto
mesh: auto

max_len: null
temperature: 0.0
top_k: -1
top_p: 1.0

peft: null
model: null
checkpoint: null

debug: False
style: rich